### ISSUE TITLE
Fairy pieces.

### ISSUE THREAD

**Issue by juliav** [wfcc/ankona#19]
Please add fairy pieces (at least, the most popular in the beginning) to the [MY PROBLEMS]->[Diagrams] - the possibility to add to the diagram, to move, to solve a problem with fairy pieces. Ready to help with the testing.

**Comment by punund** [comment]
For now, you can enjoy N, G, chinese pieces, lions, berolina.  Announcement is on site.

**Comment by juliav** [comment]
Thanks, it really works good! But neutral pieces are needed as well! Hope to have them some day...  Please reopen issue!!
