### ISSUE TITLE
Sorting/Grouping: MyProblems by purpose.

### ISSUE THREAD

**Issue by juliav** [wfcc/ankona#20]
Please add something like virtual folders or tags (either user created, or some build-in)  for [My Problems] to sort/group by purpose: like problems for solving, composing->unfinished, composing->finished, composing->published (no edit option), composing->submitted to competition (no edit option), etc. Ready to test!

**Comment by punund** [comment]
This functionality was once there, it should not be hard to put it back.

**Comment by punund** [comment]
Added personal notes and personal reference numbers, they may be treated as tags.
