### ISSUE TITLE
Security&Sharing.

### ISSUE THREAD

**Issue by juliav** [wfcc/ankona#21]
To my opinion, it shouldn't be possible to see others' problems knowing diagram's number. But it would be good to have an option of sharing a problem with others. What I'd suggest is to have the following options for a problem: 1) to share it with another user(s) of the system with no-edit possibility; 2) to share it with another user(s) of the system with edit possibility - in case of joint composing work; 3) to share with all users or to make it  "public" (with no edit option) - for browsing, searching,etc. -   this is in a case if public database is planned to be. In addition to SHARE option I'd like to have a MOVE option. It would be useful for a problems which are entered by a user (not the author of the problem) on purpose (submitting to competition, adding to the database etc)  - for not keeping it in [MyProblems] at all, but sending/moving to the "destination". Ready to test!

**Comment by punund** [comment]
Sharing implemented.
