### ISSUE TITLE
Glitch in New problem screen

### ISSUE THREAD

**Issue by fougiaxis** [wfcc/ankona#24]
After you enter a composition in the database and assign it to a section, you get a confirmation. I would propose a slight change in the wording of the message: "The composition was submitted to this competition" sounds better to me.

A glitch to be fixed: after you click to add a new entry, the confirmation message is still displayed, which may confuse some users. It should be removed.

**Comment by punund** [comment]
The wording is changed, persisting of the confirmation message cannot be reproduced.
