### ISSUE TITLE
CD can send invitation for SD in the same section to more than one user

### ISSUE THREAD

**Issue by punund** [wfcc/ankona#4]
Such an option must be available, but the CD should be warned by the system.

**Comment by punund** [comment]
Please elaborate?

**Comment by fougiaxis** [comment]
The CD can send an SD invitation to a user, even if he has already appointed a director. This is OK, as one may need a substitute SD in case of an emergency.

However it is something that the CD may also do accidentally (e.g. not making the correct selection when sending the invitation). If the user XX accepts the invitation, the system replaces the previous SD automatically. In case of a mistake, the CD can of course send again an invitation to the previous SD and fix the issue.

I think it would be better to ask the SD to confirm an SD invitation, when he has already appointed a director.

**Comment by punund** [comment]
Current section director on the invitation screen is now shown alongside the section name in the drop-down list.
Instructional wording is added before the "Invite" button.
Besides, it is shown below, in the section listing itself.
