### ISSUE TITLE
Solution is shown in a long narrow column with tiny fonts. SJ has to Ctrl+scroll to enlarge size.

### ISSUE THREAD

**Issue by punund** [wfcc/ankona#9]
Display pages to be redesigned.

**Comment by punund** [comment]
Which page are you referring to?

**Comment by fougiaxis** [comment]
The page that the judge sees.

<a href="http://imageshack.us/photo/my-images/7/displaypagetothejudge.jpg/" target="_blank"><img src="http://img7.imageshack.us/img7/2850/displaypagetothejudge.th.jpg" border="0"/></a>

The slider gets too much space.

The font size used in the solution is too small.

You can hardly read the composer's comments, as they stretch in a long thin column.

By the way, the judge cannot see the pieces count. It should be displayed.

**Comment by fougiaxis** [comment]
The judge is neither informed about the type of the fairy pieces.

This should be displayed under the diagram or alongside inside the left text frame.

**Comment by punund** [comment]
These issues are resolved.
